version: '3'

services:
  device-service:  
    image: monitoring_img
#    ports:
#      - "8082:8082"
    environment:
      - DB_IP=host.docker.internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monitoring-ms.rule=PathPrefix(`/monitoring`)"
      - "traefik.http.services.monitoring-ms.loadbalancer.server.port=8082"
    networks:
      demo_net:
        aliases:
          - monitoring-service  

  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=DEBUG"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      demo_net:
        aliases:
          - traefik-service  


networks:
  demo_net:
    external: true
