version: '3'

services:

  client-service:
    image: client_img
#    ports:
#      - "8080:8080"
    environment:
      - DB_IP=host.docker.internal
      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client-ms.rule=PathPrefix(`/client`)"
      - "traefik.http.services.client-ms.loadbalancer.server.port=8080"
      
    networks:
      demo_net:
        aliases:
          - client-service

networks:
  demo_net:
    external: true